site_name: OneEase
site_url: http://oneease.com
site_author: OneEase Inc.
site_description: >-
  OneEase - Open Source Tutorials and Projects for Smart Home

copyright: Copyright &copy; 2014 - 2020 OneEase Inc.
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - toc.integrate
    - toc.follow
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
plugins:
  - blog
  - search
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  footer:
    copyright: "Copyright &copy; 2014 - 2020 OneEase Inc."
# Page tree
nav:
  - Home: index.md
  - EaseLock:
    - About: easelock/index.md
  - EaseHome:
    - About: easehome/index.md
  - Download:
    - 00io: download/index.md
  - Blog:
    - blog/index.md

