site_name: OneEase
site_url: https://oneease.com
site_author:  Ethan Thompson in OneEase Inc. 
site_description: >-
  OneEase - Open Source Tutorials and Projects for Smart Home

copyright: Copyright &copy; 2014 - 2020 OneEase Inc.
theme:
  name: material
  custom_dir: overrides
  logo: static/logo.png
  favicon: static/favicon.ico
  features:
    - announce.dismiss
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - toc.integrate
    - toc.follow
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
extra:
  status:
    new: Recently added
    deprecated: Deprecated

# Page tree
nav:
  - Home: index.md
  - EaseCar:
    - About: easecar/index.md
    - EaseCar Tutorial: easecar/tutorial.md
    - EaseCar Download: easecar/download.md
  - EaseHome:
    - About: easehome/index.md
    - EaseHome Tutorial: easehome/tutorial.md
    - EaseHome Download: easehome/download.md
  - EaseLock:
    - Home: easelock/index.md
    - EaseLock Hardware Tutorial: easelock/hw.md
    - EaseLock Software Tutorial: easelock/app.md
    - EaseLock Download: easelock/download.md
  - EaseRobot:
    - EaseRobot Home: easerobot/index.md
    - Tutorial Part1: easerobot/p1.md
    - Tutorial Part2: easerobot/p2.md
    - Tutorial Part3: easerobot/p3.md
    - Tutorial Part4: easerobot/p4.md
    - Tutorial Part5: easerobot/p5.md
    - Tutorial Part6: easerobot/p6.md
    - Tutorial Part7: easerobot/p7.md
    - Tutorial Part8: easerobot/p8.md
    - EaseRobot Download: easerobot/download.md
  - EaseWatcher:
    - Home: easewatcher/index.md
    - EaseWatcher Tutorial: easewatcher/tutorial.md
    - EaseWatcher Download: easewatcher/download.md
  - Community:
    - community/index.md

